title: Stimulus

description: >-
  Stimulus is a JavaScript framework with modest ambitions. It doesn't seek to take over your entire front-end—in fact, it's not concerned with rendering HTML at all. Instead, it's designed to augment your HTML with just enough behavior to make it shine. Stimulus pairs beautifully with Turbolinks to provide a complete solution for fast, compelling applications with a minimal amount of effort.

collections:
  handbook:
    output: true
    permalink: /:collection/:name

exclude:
  - Gemfile
  - Gemfile.lock
