title: Stimulus

description: >-
  Stimulus is a JavaScript framework with modest ambitions. It doesn't seek to take over your entire front-end—in fact, it's not concerned with rendering HTML at all. Instead, it's designed to augment your HTML with just enough behavior to make it shine. Stimulus pairs beautifully with Turbolinks to provide a complete solution for fast, compelling applications with a minimal amount of effort.

theme: false

collections:
  handbook:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      type: handbook
    values:
      collection_title: Handbook
      layout: handbook

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: true

exclude:
  - node_modules
  - .babelrc
  - Gemfile
  - Gemfile.lock
  - package.json
  - webpack.config.js
  - yarn.lock
