title: Stimulus
url: https://stimulusjs.org
discourse_url: https://discourse.stimulusjs.org
github_url: https://github.com/stimulusjs/stimulus
description: The speed of a single-page web application without having to write any JavaScript.

theme: false

defaults:
  - scope:
      path: "*/handbook/*"
    values:
      section: handbook
      section_title: Handbook
      layout_type: docs
      layout: docs
  - scope:
      path: "*/reference/*"
    values:
      section: reference
      section_title: Reference
      layout_type: docs
      layout: docs

optional_front_matter:
  remove_originals: true

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: true

exclude:
  - node_modules
  - bin
  - .babelrc
  - Gemfile
  - Gemfile.lock
  - now-build.sh
  - now.json
  - package.json
  - webpack.config.js
  - yarn.lock

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
