name: Eleventy Publish
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.7.0
      - run: npm ci
      - run: npm run publish
      # These provide handy aliases to some pages
      - run: ln -s _public/handbook/introduction.html _public/handbook/index.html 
      - run: ln -s _public/reference/controllers.html _public/reference/index.html 
      - run: ln -s _public/reference/values.html _public/reference/data-maps.html 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_public
